spring:
  datasource:
    url: jdbc:mariadb://webservice.c7lmmj1i3i2l.ap-northeast-2.rds.amazonaws.com:3306/webservice
    username: hugebird
    password: 5ab5c87a
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #        show_sql: true
        format_sql: true
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            authorization-grant-type: authorization_code
#            client-id: 0424bf7b6fda69a5ef3c591a8d4f0f43
#            client-secret: sDJBDCqev1qYhyE83Fw3NQkyNFjiLDJF
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - profile
#              - account_email
#            client-authentication-method: POST
#            client-name: Kakao
#
#        provider:
#
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#            user-info-authentication-method: POST
logging:
  level:
    org.hibernate.SQL: debug